server:
  port:
    80
spring:
  application:
    name: cloud-orderconsul-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lijun896
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ilife.springcloud.entities
